### PR TITLE
Feature/wrong anwers registration

### LINKED ISSUE #17: REQ-016: Wrong Questions Review System
# Wrong Questions Review System

## Description
Create a system to store and review questions answered incorrectly during gameplay using a doubly linked list.

### Interface Format
```
==============================
GAME OVER!
Would you like to review your 
wrong answers? (Y/N): _

[If Yes Selected]
Wrong Answer Review (1 of X)
Question: [Question Text]
Your Answer: [Player Answer]
Correct Answer: [Correct Answer]

1. Next
2. Previous
3. Exit Review
==============================
```

### Core Features
* Create auxiliary doubly linked list for wrong answers
* Store questions missed during gameplay
* End-of-game review option
* Navigation through wrong answers:
  - Next question
  - Previous question
  - Exit review

### Integration Requirements
1. During Gameplay:
   - Track wrong answers
   - Store player's incorrect choice
   - Maintain question details

2. Review System:
   - Bidirectional navigation
   - Show original question
   - Display player's wrong answer
   - Show correct answer

### PR DESCRIPTION
**Pull request by HiramAAH**
A new functionality was implemented in the program to record incorrect answers during the game. The new InsertWrongAnswer function allows storing the data of an incorrectly answered question, together with the option selected by the user and the correct answer, in a doubly linked list. This facilitates subsequent analysis of errors made during the game.

### CODE REVIEW

**Review by gfdfranco — APPROVED** [review]
LGTM

**Comment by gfdfranco** [comment]
We need to refacto a lot of things in this code. but it can handle when we merge this with other branches.

**Review by Friedamariao — APPROVED** [review]

**Comment by Friedamariao** [comment]
Looks good to me overall! I also think some parts could be refactored for clarity, though,  other than that, it's great!

**Review by CristianSagahon — APPROVED** [review]
LGTM. Nonetheless, I feel the same way, that a lot of things need to be refactored to make it clearer, but it looks very good!

**Pull request merged**
